name: ecommerceaudio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2

  #UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  fonts:
    - family: DmSans
      fonts:
        - asset: assets/fonts/DmSans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DmSans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DmSans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DmSans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DmSans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DmSans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DmSans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DmSans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DmSans/DMSans-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
