name: ecommerceaudio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #Network
  dio: ^5.7.0

  #State Management
  flutter_bloc: ^8.1.6

  #Navigation
  auto_route: ^9.2.2

  #UI
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.14
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1

  #Utils
  google_sign_in: ^6.2.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  logger: ^2.5.0
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

  #test
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/oauth/
    - assets/images/
    - assets/translations/

  fonts:
    - family: DmSans
      fonts:
        - asset: assets/fonts/DmSans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DmSans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DmSans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DmSans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DmSans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DmSans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DmSans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DmSans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DmSans/DMSans-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
